"use strict";
var compo = compo||{};
compo={
		cust_login : ()=>{
			return '<h2>Responsive Social Login Form</h2>'
			+'<p>Resize the browser window to see the responsive effect. When the screen is less than 650px wide, make the two columns stack on top of each other instead of next to each other.</p>'
			
			+'<div class="container">'
			+'  <form>'
			+'    <div class="row">'
			+'      <h2 style="text-align:center">Login with Social Media or Manually</h2>'
			+'      <div class="vl">'
			+'        <span class="vl-innertext">or</span>'
			+'      </div>'
			
			+'      <div class="col">'
			+'        <a href="#" class="fb btn">'
			+'          <i class="fa fa-facebook fa-fw"></i> Login with Facebook'
			+'         </a>'
			+'        <a href="#" class="twitter btn">'
			+'          <i class="fa fa-twitter fa-fw"></i> Login with Twitter'
			+'        </a>'
			+'        <a href="#" class="google btn"><i class="fa fa-google fa-fw">'
			+'          </i> Login with Google+'
			+'        </a>'
			+'      </div>'
			
			+'      <div class="col">'
			+'        <div class="hide-md-lg">'
			+'          <p>Or sign in manually:</p>'
			+'        </div>'
			+''
			+'        <input type="text" name="customerID" placeholder="ID" required>'
			+'        <input type="password" name="password" placeholder="Password" required>'
			+'        <input type="submit" value="Login">'
			+'      </div>'
			
			+'    </div>'
			+'  </form>'
			+'</div>'
			
			+'<div class="bottom-container">'
			+'  <div class="row">'
			+'    <div class="col">'
			+'      <a href="#" style="color:white" class="btn">회원 가입</a>'
			+'    </div>'
			+'    <div class="col">'
			+'      <a href="#" style="color:white" class="btn">아이디/비번찾기</a>'
			+'    </div>'
			+'  </div>'
			+'</div>';
		},
		login_in : ()=>{
			return '<div id="maincontent" class="container-fluid bg-3 text-center">'
			+'  <h3>Some of my Work</h3><br>'
			+'  <div class="row">'
			+'    <div class="col-sm-3">'
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3"> '
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3"> '
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3">'
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'  </div>'
			+'</div><br>'

			+'<div id="maincontent1" class="container-fluid bg-3 text-center">    '
			+'  <div class="row">'
			+'    <div class="col-sm-3">'
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3"> '
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3"> '
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'    <div class="col-sm-3">'
			+'      <p>Some text..</p>'
			+'      <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">'
			+'    </div>'
			+'  </div>'
			+'</div><br><br>';
		}
}